routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');





Auth::routes();

/**
 * All admin routes
 */
Route::group(['prefix' => 'admin'], function (){
    Route::get('/', 'AdminController@index')->name('admin');

    // Category routes
    Route::get('category/search', [
        'uses' => 'CategoryController@search',
        'as' => 'admin.category.search'
    ]);
    Route::resource('/category', 'CategoryController',[
        'except' => ['destroy']
    ])->names('admin.category');
    Route::get('category/{id}/delete',[
        'uses' => 'CategoryController@delete',
        'as' => 'admin.category.delete'
    ]);

    // Tag routes
    Route::get('tag/search', [
        'uses' => 'TagController@search',
        'as' => 'admin.tag.search'
    ]);
    Route::resource('/tag', 'TagController',[
        'except' => ['destroy']
    ])->names('admin.tag');
    Route::get('tag/{id}/delete',[
        'uses' => 'TagController@delete',
        'as' => 'admin.tag.delete'
    ]);

    // Post routes
    Route::get('post/search', [
        'uses' => 'PostController@search',
        'as' => 'admin.post.search'
    ]);
    Route::resource('/post', 'PostController',[
        'except' => ['destroy']
    ])->names('admin.post');

    Route::get('post/{id}/delete',[
        'uses' => 'PostController@delete',
        'as' => 'admin.post.delete'
    ]);
    Route::get('post/{id}/publish',[
        'uses' => 'PostController@publish',
        'as' => 'admin.post.publish'
    ]);

    // User routes
    Route::get('/user',[
        'uses' => 'AdminController@list',
        'as' => 'admin.user.index'
    ]);
    Route::get('/user/create',[
        'uses' => 'AdminController@create',
        'as' => 'admin.user.create'
    ]);
    Route::post('/user',[
        'uses' => 'AdminController@store',
        'as' => 'admin.user.store'
    ]);

});

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
</footer>

resources/views/admin/partials/logo.blade.php
<a href="{{route('home')}}" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>C</b>MS</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>L55</b>CMS</span>
</a>

resources/views/admin/partials/navTop.blade.php
<nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {{--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">--}}
                    <span class="hidden-xs"> Welcome {{Auth::user()->name}}</span>
                </a>
                <ul class="dropdown-menu">
                    <!-- User image -->
                    <li class="user-header">
                        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                        <p>
                            Alexander Pierce - Web Developer
                            <small>Member since Nov. 2012</small>
                        </p>
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <div class="pull-left">
                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                        </div>
                        <div class="pull-right">
                            <a href="#" class="btn btn-default btn-flat">Sign out</a>
                        </div>
                    </li>
                </ul>
            </li>
            <!-- Control Sidebar Toggle Button -->
            {{--<li>--}}
                {{--<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>--}}
            {{--</li>--}}
        </ul>
    </div>
</nav>

resources/views/admin/partials/pageHeader.blade.php
<section class="content-header">

    <div class="col-lg-3">
        <h2>
            @if(isset($data_title))
                {{$data_title}}
            @else
                Dashboard
            @endif
        </h2>
    </div>
    {{-- Search form --}}
    @include('admin.partials.search')
    <div class="col-lg-3 pull-right">
     @include('admin.partials.topButtons')
    </div>
</section>
<div class="clearfix"></div>

resources/views/admin/partials/scripts.blade.php
<!-- jQuery 3 -->
<script src="{{asset('backend/js/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('backend/js/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('backend/js/bootstrap.min.js')}}"></script>
<!-- Morris.js charts -->
<script src="{{asset('backend/js/raphael.min.js')}}"></script>
<script src="{{asset('backend/js/morris.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('backend/js/jquery.sparkline.min.js')}}"></script>
<!-- jvectormap -->
<script src="{{asset('backend/js/jquery-jvectormap-1.2.2.min.js')}}"></script>
<script src="{{asset('backend/js/jquery-jvectormap-world-mill-en.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('backend/js/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('backend/js/moment.min.js')}}"></script>
<script src="{{asset('backend/js/daterangepicker.js')}}"></script>
<!-- datepicker -->
<script src="{{asset('backend/js/bootstrap-datepicker.min.js')}}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{asset('backend/js/bootstrap3-wysihtml5.all.min.js')}}"></script>
<!-- Slimscroll -->
<script src="{{asset('backend/js/jquery.slimscroll.min.js')}}"></script>
<!-- FastClick -->
<script src="{{asset('backend/js/fastclick.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('backend/js/adminlte.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('backend/js/dashboard.js')}}"></script>

resources/views/admin/partials/search.blade.php
<div class="col-md-6">
    <div class="col-lg-8 col-lg-offset-2">
        <h2>
            <form method="GET" action="{{$search_route ?? ''}}" role="search">
                <div class="input-group">
                    <input type="text" placeholder="search" name="s" class="form-control" required>
                    <span class="input-group-btn">
            <button type="submit" class="btn btn-flat">
            <i class="fa fa-search"></i>
            </button>
            </span>
                </div>
            </form>
        </h2>

    </div>
</div>

resources/views/admin/partials/sideBar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search for post or page...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="treeview">
                <a href="{{route('admin')}}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li class=" treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Media</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Images</a></li>
                    <li><a href="index2.html"><i class="fa fa-circle-o"></i> Files</a></li>
                </ul>
            </li>
            <li class=" treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Posts</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="{{route('admin.post.create')}}"><i class="fa fa-circle-o"></i> New post</a></li>
                    <li><a href="{{route('admin.post.index')}}"><i class="fa fa-circle-o"></i> All posts</a></li>
                </ul>
            </li>
            <li>
                <a href="pages/calendar.html">
                    <i class="fa fa-calendar"></i> <span>Comments</span>
                </a>
            </li>
            <li>
                <a href="{{route('admin.tag.index')}}">
                    <i class="fa fa-tags"></i> <span>Tags</span>
                </a>
            </li>
            <li class=" treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Categories</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.category.index')}}"><i class="fa fa-circle-o"></i> All categories</a></li>
                    <li class="active"><a href="{{route('admin.category.create')}}"><i class="fa fa-circle-o"></i> New category</a></li>
                </ul>
            </li>
            <li class=" treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Content</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Page</a></li>
                    <li><a href="index2.html"><i class="fa fa-circle-o"></i> Menu</a></li>
                    <li><a href="index2.html"><i class="fa fa-circle-o"></i> Widgets</a></li>
                </ul>
            </li>
            <li class=" treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Settings</span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Users</a></li>
                    <li><a href="index2.html"><i class="fa fa-circle-o"></i> Config</a></li>
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/admin/partials/styles.blade.php
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{asset('backend/css/bootstrap.min.css')}}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{asset('backend/css/font-awesome.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{asset('backend/css/ionicons.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('backend/css/AdminLTE.min.css')}}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{asset('backend/css/_all-skins.min.css')}}">
<!-- Morris chart -->
<link rel="stylesheet" href="{{asset('backend/css/morris.css')}}">
<!-- jvectormap -->
<link rel="stylesheet" href="{{asset('backend/css/jquery-jvectormap.css')}}">
<!-- Date Picker -->
<link rel="stylesheet" href="{{asset('backend/css/bootstrap-datepicker.min.css')}}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{asset('backend/css/daterangepicker.css')}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{asset('backend/css/bootstrap3-wysihtml5.min.css')}}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/admin/partials/topButtons.blade.php
<h2>
    @if(isset($data_top_buttons) && count($data_top_buttons) > 0)
        @foreach($data_top_buttons as $top_button)
            <a href="{{$top_button['url']}}" class="btn btn-md btn-{{$top_button['class']}}">{{$top_button['value']}}</a>
        @endforeach
    @endif
</h2>